Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@egilbertson-ucsf 
ucsf-bmi-203-2021
/
Project2
1
010
Code
Issues
Pull requests
1
Actions
Projects
Wiki
Security
Insights
Project3/.github/workflows/test.yml
@laurashub
laurashub starting files
Latest commit ab8755e 27 days ago
 History
 1 contributor
33 lines (25 sloc)  860 Bytes
  
# This is a basic workflow to help you get started with Actions

name: HW3

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6 
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run unit tests
        run: python -m pytest -v test/*
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
